/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/framer/how-do-i-code-animations/app-store-like-transition': RouteRecordInfo<'/framer/how-do-i-code-animations/app-store-like-transition', '/framer/how-do-i-code-animations/app-store-like-transition', Record<never, never>, Record<never, never>>,
    '/framer/how-do-i-code-animations/shared-layout-modals': RouteRecordInfo<'/framer/how-do-i-code-animations/shared-layout-modals', '/framer/how-do-i-code-animations/shared-layout-modals', Record<never, never>, Record<never, never>>,
    '/framer/how-do-i-code-animations/show-second': RouteRecordInfo<'/framer/how-do-i-code-animations/show-second', '/framer/how-do-i-code-animations/show-second', Record<never, never>, Record<never, never>>,
  }
}
